### ISSUE TITLE
add ride and add tracking endpoints

### ISSUE THREAD

**Issue by RensVanGiersbergen** [RensVanGiersbergen/skatetracker#4]
- [x] Add ride endpoint
- [x] Add tracking to ride endpoint
- [x] Update ride endpoint
- [x] Delete ride endpoint
- [x] Get ride
- [x] Get all my rides (pagination)
