### ISSUE TITLE
Add tracking feature to frontend

### ISSUE THREAD

**Issue by RensVanGiersbergen** [RensVanGiersbergen/skatetracker#7]
- [ ] Simple login/register
- [ ] Create ride
- [ ] Finish ride
- [ ] See all rides
- [ ] Get ride
- [ ] Delete ride
- [ ] Stores for State management
